networks:
  duckinzzz_net:
    name: duckinzzz_net
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: duckinzzz_web_dev
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - duckinzzz_net

  celery:
    build:
      context: .
      dockerfile: dev.Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - duckinzzz_net
    command: celery -A config worker --loglevel=info --concurrency=2

  redis:
    image: redis:alpine
    container_name: duckinzzz_redis_dev
    ports:
      - "6379:6379"
    networks:
      - duckinzzz_net

volumes:
  static_volume:
  media_volume: