x-app-image: &app-image ghcr.io/duckinzzz/duckinzzz.ru:latest

services:
  web:
    image: *app-image
    container_name: duckinzzz_web
    mem_limit: 180m
    cpus: 0.3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"
    entrypoint: [ "/bin/bash", "/app/entrypoint.sh" ]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - duckinzzz_net

  celery:
    image: *app-image
    container_name: duckinzzz_celery
    mem_limit: 120m
    cpus: 0.2
    env_file:
      - .env
    depends_on:
      - redis
      - web
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - duckinzzz_net
    entrypoint: [ ]
    command: celery -A config worker --loglevel=warning --concurrency=1 --max-tasks-per-child=50
    restart: unless-stopped

  celery-beat:
    image: *app-image
    container_name: duckinzzz_celery_beat
    mem_limit: 80m
    cpus: 0.1
    command: celery -A config beat --loglevel=warning
    env_file:
      - .env
    depends_on:
      - redis
      - web
    networks:
      - duckinzzz_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: duckinzzz_redis
    networks:
      - duckinzzz_net
    restart: unless-stopped
    command: redis-server --maxmemory 50mb --maxmemory-policy allkeys-lru --save "" --appendonly no

  nginx:
    image: nginx:alpine
    container_name: duckinzzz_nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - duckinzzz_net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.duck_site.rule=Host(`duckinzzz.ru`) || Host(`www.duckinzzz.ru`)"
      - "traefik.http.routers.duck_site.entrypoints=websecure"
      - "traefik.http.routers.duck_site.tls=true"
      - "traefik.http.services.duck_site.loadbalancer.server.port=80"

networks:
  duckinzzz_net:
    driver: bridge
  proxy:
    external: true

volumes:
  static_volume:
  media_volume: