# docker compose -f docker-compose.prod.yml up -d --build
networks:
  duckinzzz_net:
    name: duckinzzz_net
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: duckinzzz_web_dev
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - duckinzzz_net

  celery:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - web
    networks:
      - duckinzzz_net
    entrypoint: [ ]  # Clear any inherited entrypoint
    command: celery -A config worker --loglevel=info --concurrency=2
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M


  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - web
    networks:
      - duckinzzz_net

  redis:
    image: redis:alpine
    container_name: duckinzzz_redis
    ports:
      - "6379:6379"
    networks:
      - duckinzzz_net

#  nginx:
#    image: nginx:alpine
#    container_name: duckinzzz_nginx
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "50m"
#        max-file: "3"
#    ports:
#      - "8000:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
#      - static_volume:/app/static:ro
#      - media_volume:/app/media:ro
#    depends_on:
#      - web
#    restart: unless-stopped
#    networks:
#      - duckinzzz_net

volumes:
  static_volume:
  media_volume:
